# Viral Ecology of Avian Influenza Viruses in Waterfowl of the Central Valley of California using MinION Sequencing

## Script: pipeline_development.rmd
This R markdown notebook is the centralized place to develop the analysis pipeline for water, swab, and soil samples

This script is part of the following manuscript:
### "Prevalence and Viral Ecology of Avian Influenza of Waterfowl in the Central Valley of California"  
###Madeline M. McCuen | Maurice E. Pitesky | Jeff J. Buler | Sarai Acosta | Alexander Wilcox | Ronald F. Bond | Samuel L. Díaz-Muñoz


# Pipeline 
1. Basecall and Demultiplex
2.

First, please review the README file in the repository to configure your environment properly. 
Ok, on with the script :) 

# 1. Sequecing Data Description and Processing

## 1.1 Data Description
One hundred seventy-five swab samples were collected from live-trapped or hunter-killed waterfowl in two wetland basins in the Central Valley of California: the Delevan National Wildlife Refuge and the Sacramento National Wildlife Refuge Complex. 

RNA was extracted from these swab samples (per bird: one pharyngeal and one cloacal, which were stored in the same tube, thus pooled) and amplified using universal Influenza A primers (Zhou et al 2009), but modified with tails to use the Oxford Nanopore PCR barcoding kit. Resulting amplicons were sequenced in two separate, new MinION flow cells (R.10.4) using Q20+ chemistry.

## 1.2 Basecalling and Demultiplexing
This step requires access to the raw fast5 files and a high performance GPU. The repository mostly starts analysis after files have been basecalled and demultiplexed. 

First generate statistics on raw fast5 files
```{bash}
#Count fast5 reads
```

Second, basecall and demultiplex reads

```{bash}
#Make sure to run recursive, including all folders in each run
#Make sure to include read-splitting in the basecalling or demultiplexing command
#Remember have two runs that share barcodes, so have to process separately and append run name to the front
#Include calibration: ask Ivy if she included in run

#Run 1 Basecalling 
~/ont-guppy/bin/guppy_basecaller --input_path /mnt/data0/MinION_reads/pitesky_avian_samples1/pitesky_avian_samples1 --save_path /mnt/data0/sam/pitesky_avian_samples1/fastq_hac --config dna_r10.4_e8.1_hac.cfg -x cuda:all:100% --num_callers 256 --recursive --calib_detect
#Looks like read-splitting in basecalling not avail on Guppy 5.11?

#Start here on demultiplexing Oct 28, 2022

#Run 1 Demultiplexing
~/ont-guppy/bin/guppy_barcoder --require_barcodes_both_ends -i /mnt/data0/MinION_reads/pitesky_avian_samples1_cp/pitesky_avian_samples1/20211216_1317_MN23913_FAR27359_f42a3dea/fastq_sac_cd/split_pass -s /mnt/data0/MinION_reads/pitesky_avian_samples1_cp/pitesky_avian_samples1/20211216_1317_MN23913_FAR27359_f42a3dea/fastq_sac_cd/demultiplexed_split_pass --arrangements_files "barcode_arrs_pcr12.cfg barcode_arrs_pcr96.cfg" -x cuda:0 --worker_threads 8

#Run 2 Basecalling
~/ont-guppy/bin/guppy_basecaller --input_path /mnt/data0/MinION_reads/pitesky_avian_samples1_cp/pitesky_avian_samples1/no_sample/20211217_1150_MN23913_FAR27359_a1bdbce7/fast5_pass/ --save_path /mnt/data0/MinION_reads/pitesky_avian_samples1_cp/pitesky_avian_samples1/no_sample/20211217_1150_MN23913_FAR27359_a1bdbce7/fastq_hac_cd --calib_detect --config dna_r10.4_e8.1_hac.cfg -x cuda:0 --num_callers 8

#Run 2 Demultiplexing
~/ont-guppy/bin/guppy_barcoder --require_barcodes_both_ends -i /mnt/data0/MinION_reads/pitesky_avian_samples1_cp/pitesky_avian_samples1/20211216_1317_MN23913_FAR27359_f42a3dea/fastq_sac_cd/split_pass -s /mnt/data0/MinION_reads/pitesky_avian_samples1_cp/pitesky_avian_samples1/20211216_1317_MN23913_FAR27359_f42a3dea/fastq_sac_cd/demultiplexed_split_pass --arrangements_files "barcode_arrs_pcr12.cfg barcode_arrs_pcr96.cfg" -x cuda:0 --worker_threads 8
```

## 1.3 Basecalling and Demultiplexing Statistics

```{bash}

```

## 3. Franklin HPC Setup and Data Upload

```{bash}
#Login to Franklin HPC
ssh sldmunoz@franklin.hpc.ucdavis.edu

#Have to load conda as a module
module load conda/base


#Slurm interactive
srun -c 1 -t 12:00:00 --mem=10000 --pty /bin/bash

#This job is just to set up data and working directories

#Make directory in Franklin to put demultiplexed_basecalled reads
cd /group/sldmunozgrp

mkdir /group/sldmunozgrp/demultiplexed_basecalled/



#Moving data to Franklin into our lab folder
#IN LOCAL TERMINAL
#60_40
#scp -rp /Users/mixtup/MinION_reads/demultiplexed_basecalled/dvg_drug_screen_ile_v2/double_barcodes_60_40 sldmunoz@franklin.hpc.ucdavis.edu:/group/sldmunozgrp/demultiplexed_basecalled/dvg_drug_screen_ile_v2/

#40_40
#scp -rp /Users/mixtup/MinION_reads/demultiplexed_basecalled/dvg_drug_screen_ile_v2/double_barcodes_40_40 sldmunoz@franklin.hpc.ucdavis.edu:/group/sldmunozgrp/demultiplexed_basecalled/dvg_drug_screen_ile_v2/

```